[build-system]
build-backend = "setuptools.build_meta"
requires = [
     "setuptools >= 61.0"
]

[project]
name = "langgraph-aipy"
version = "0.3.18"
description = "Building stateful, multi-actor applications with LLMs"
readme = "README.md"
license = {text = "MIT AND (Apache-2.0 OR BSD-2-Clause)"}
requires-python = "==3.12.*"
authors = [
    { name = "The QPYPI Team", email = "qpypi@qpython.org" },
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Information Technology",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: Android",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development",
]
dependencies = [
    "httpx", "orjson-qpython", "msgpack-qpython", "langchain-core-aipy"
]

[project.urls]
Homepage = "https://qpypi.qpython.org/project/langgraph-aipy/"