[project]
name = "nonebot-plugin-pokemonle"
version = "0.0.3"
description = "猜宝可梦"
authors = [
    { name = "Proito666", email = "Proito666@github.com" },
]
license = "MIT"
readme = "README.md"
dependencies = [
    "nonebot2<3.0.0,>=2.3.0",
    "nonebot-plugin-htmlrender<1.0.0,>=0.2.0",
    "nonebot-plugin-alconna<1.0.0,>=0.25.0",
    "pypinyin>=0.54.0",
    "nonebot-plugin-uninfo>=0.7.3",
    "jinja2>=3.1.6",
]
requires-python = "<4.0,>=3.9"

[project.urls]
repository = "https://github.com/Proito666/nonebot-plugin-pokemonle"

[tool.pdm.build]
package-dir = "."
includes = [
    "nonebot_plugin_pokemonle",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
