[project]
name = "suse-documentation-mcp-server"
version = "0.28.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]~=1.6.0",
    "pydantic>=2.10.3",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]

[project.scripts]
suse-documentation-mcp-server = "server.search_suse_documentation:main"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
