[build-system]
requires = ["setuptools>=77.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flasktunnel-client"
version = "1.0.3"
description = "Client pour créer des tunnels HTTP sécurisés vers vos applications locales"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "Mohamed Ndiaye", email = "mouhamedndiayegroupeisi@gmail.com"},
]
keywords = ["tunnel", "ngrok", "flask", "django", "development", "webhook", "localhost", "http", "https"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Testing",
    "Topic :: System :: Networking",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.0",
    "python-socketio[client]>=5.0.0",
    "colorama>=0.4.4",
    "click>=8.0.0",
    "cryptography>=3.4.0",
    "websocket-client>=1.0.0",
]

[project.urls]
Homepage = "https://flasktunnel.up.railway.app/"
Documentation = "https://docs.flasktunnel.dev"
Repository = "https://github.com/Moesthetics-code/flasktunnel-client.git"
"Bug Tracker" = "https://github.com/Moesthetics-code/flasktunnel-client/issues"

[project.scripts]
flasktunnel = "flasktunnel.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["flasktunnel*"]

[tool.setuptools.package-data]
flasktunnel = ["*.json", "*.txt", "*.md"]