[project]
name = "aos8_api"
version = "8.9.3post1"
description = "OmniSwitch RestFUL API for Python"
authors = [{ name = "Samuel Yip", email = "kahyean.yip@gmail.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "httpx>=0.24.1",
    "requests>=2.31.0",
    "pydantic>=2.0",
    "pybreaker>=0.7.0",
    "backoff>=2.2.1"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["endpoints"]