[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pgarrow"
version = "v0.0.7"
authors = [
  { name="Michal Charemza", email="michal@charemza.name" },
]
description = "A SQLAlchemy PostgreSQL dialect for ADBC (Arrow Database Connectivity)"
readme = "README.md"
requires-python = ">=3.7.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Topic :: Database",
]
dependencies = [
    "sqlalchemy>=1.4.24,!=2.0.0,!=2.0.1,!=2.0.2,!=2.0.3,!=2.0.4,!=2.0.5,!=2.0.6;python_version<'3.13'",
    "sqlalchemy>=1.4.24,!=2.0.0,!=2.0.1,!=2.0.2,!=2.0.3,!=2.0.4,!=2.0.5,!=2.0.6,!=2.0.7,!=2.0.8,!=2.0.9,!=2.0.10,!=2.0.11,!=2.0.12,!=2.0.13,!=2.0.14,!=2.0.15,!=2.0.16,!=2.0.17,!=2.0.18,!=2.0.19,!=2.0.20,!=2.0.21,!=2.0.22,!=2.0.23,!=2.0.24,!=2.0.25,!=2.0.26,!=2.0.27,!=2.0.28,!=2.0.29,!=2.0.30,!=2.0.31,!=2.0.32,!=2.0.33,!=2.0.34,!=2.0.35,!=2.0.36,!=2.0.37,!=2.0.38,!=2.0.39,!=2.0.40;python_version>='3.13'",
    "adbc-driver-postgresql>=1.6.0",
    "pyarrow>=15.0.0;python_version<'3.13'",
    "pyarrow>=18.0.0;python_version>='3.13'",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.2.1",
    "pytest-cov",
]
ci = [
    "pytest",
    "pytest-cov",
    "adbc-driver-postgresql==1.6.0",
]
"ci-pyarrow-15.0.0" = [
    "pyarrow==15.0.0",
]
"ci-pyarrow-16.0.0" = [
    "pyarrow==16.0.0",
]
"ci-pyarrow-17.0.0" = [
    "pyarrow==17.0.0",
]
"ci-pyarrow-18.0.0" = [
    "pyarrow==18.0.0",
]
"ci-pyarrow-19.0.0" = [
    "pyarrow==19.0.0",
]
"ci-pyarrow-20.0.0" = [
    "pyarrow==20.0.0",
]
"ci-sqlalchemy-1" = [
   "sqlalchemy==1.4.24",
]
"ci-sqlalchemy-2" = [
    "sqlalchemy==2.0.7;python_version<'3.13'",
    "sqlalchemy==2.0.41;python_version>='3.13'",
]

[project.urls]
"Source" = "https://github.com/michalc/pgarrow"

[tool.hatch.build]
include = [
  "pgarrow.py"
]

[project.entry-points."sqlalchemy.dialects"]
"postgresql.pgarrow" = "pgarrow:PgDialect_pgarrow"
