[build-system]
requires = [ "setuptools>=61.0", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "bexy"
version = "0.1.26"
description = "A sandbox for safely running Python code"
readme = "README.md"
requires-python = ">=3.8,<4.0"
classifiers = [ "Development Status :: 3 - Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.8", "Programming Language :: Python :: 3.9", "Programming Language :: Python :: 3.10", "Programming Language :: Python :: 3.11", "Programming Language :: Python :: 3.12", "Topic :: Software Development :: Interpreters", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: Security",]
dependencies = []
[[project.authors]]
name = "Tom Sapletta"
email = "info@softreck.dev"

[project.license]
text = "Apache-2.0"

[project.optional-dependencies]

[project.urls]
Homepage = "https://github.com/py-lama/bexy"
Documentation = "https://py-lama.github.io/bexy/"
Repository = "https://github.com/py-lama/bexy"
Changelog = "https://github.com/py-lama/bexy/blob/main/CHANGELOG.md"
Tracker = "https://github.com/py-lama/bexy/issues"
Download = "https://pypi.org/project/bexy/"

[tool.setuptools]
packages = [ "bexy",]
include-package-data = true
