[project]
name = "cobaldeval"
version = "1.0.2"
description = "CoBaLD evaluation script"
requires-python = ">=3.12"
license-files = ["LICENSE"]
dependencies = [
    "numpy>=1.20.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1"
]

[project.scripts]
cobaldeval = "cobaldeval.evaluate:main"

[tool.setuptools]
packages = ["cobaldeval"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"