[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cobaldeval"
version = "1.0.5"
description = "CoBaLD evaluation script"
requires-python = ">=3.12"
license-files = ["LICENSE"]
dependencies = [
    "numpy>=1.20.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1"
]

[project.scripts]
cobaldeval = "cobaldeval.evaluate:main"  # Clean import path!

[tool.setuptools]
packages = ["cobaldeval"]
package-dir = {"" = "src"}  # Critical: Tells setuptools to look in src/

[tool.setuptools.package-data]
"cobaldeval" = ["res/*"]  # Include package resources