[project]
name = "mgplot"
version = "0.1.3"
description = "mgplot is a time-series/PeriodIndex frontend for matplotlib"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    # - system
    "typing",
    "pathlib",

    # - data science 
    "matplotlib",
    "numpy",
    "pandas",
    "tabulate",

    # - development environment
    "black",
    "mypy",
    "pdoc",
    "pylint",
    "ruff",

    # - typing
    "pandas-stubs",
    "numpy-typing",
    "types-tabulate",
]

[project.optional-dependencies]
build = ["setuptools", "cython"]

[project.urls]
Homepage = "https://github.com/bpalmer4/mgplot"


