[tool.poetry]
name = "langraph_api"
version = "0.0.9"
description = "LangGraph Azure Function Agents"
authors = ["Example <example@example.com>"]
packages = [
    
    { include = "langraph_api" }
]

[tool.poetry.dependencies]
python = "^3.10"
azure-functions = "*"
pydantic = "*"
openai-agents = "*"
langchain = "*"
langgraph = "*"
langchain_community = "*"
langchain-core = "*"
openapi-schema-pydantic = "*"
requests = "*"
dacite = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.0"
myst-parser = "^0.18"
toml = "^0.10"    # ‚Üê add this line