[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "abf_openai"
version = "0.0.6"
dependencies = [
    "requests>=2.32.2",
    "tqdm>=4.67.1",
    "openai>=1.66.2",
]
authors = [
  { name="Daniel Guetta", email="daniel@guetta.com" },
]
description = "A version of the OpenAI package for the Columbia Business School and Wall Street Prep AI in Business and Finance program"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://wallstreetprep.business.columbia.edu/ai-certification/"