[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PHITS-Tools"
version = "1.5.1"
description = 'Python module for parsing and post-processing output from the PHITS code'
readme = "README.md"
license = "MPL-2.0"
license-files = ["LICENSE"]
keywords = []
authors = [
  { name = "Lindt8", email = "Lindt8@users.noreply.github.com" },
]
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = ["numpy>=2.2.1", "pandas>=2.2.3", "scipy>=1.14.1", "matplotlib>=3.10.0", "seaborn>=0.13.2"]

[project.urls]
Documentation = "https://github.com/Lindt8/PHITS-Tools#readme"
Issues = "https://github.com/Lindt8/PHITS-Tools/issues"
Source = "https://github.com/Lindt8/PHITS-Tools"
