[project]
name = "llm-tools-mcp"
version = "0.1.0a1"
description = "MCP support for LLM CLI"
readme = "README.md"
authors = [{name = "Michal Fudala"}]
license = "Apache-2.0"
classifiers = []
requires-python = ">=3.10"
dependencies = [
    "llm",
    "mcp[cli]>=1.9.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/VirtusLab/llm-tools-mcp"
Changelog = "https://github.com/VirtusLab/llm-tools-mcp/releases"
Issues = "https://github.com/VirtusLab/llm-tools-mcp/issues"
CI = "https://github.com/VirtusLab/llm-tools-mcp/actions"

[project.entry-points.llm]
mcp = "llm_tools_mcp"

[project.optional-dependencies]
test = ["pytest"]
