[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "compliant-llm"
version = "0.1.7"
description = "Tool for testing AI system prompts against various attack vectors"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Compliant LLM Contributors", email = "example@example.com"},
]
dependencies = [
    "pyyaml",
    "streamlit",
    "click",
    "rich",
    "litellm",
    "python-dotenv",
    "pytest",
    "aiofiles",
    "plotly",
    "psutil",
    "markdown",
    "opentelemetry-api",
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp",
    "opentelemetry-instrumentation",
    "azure-monitor-opentelemetry-exporter",
    "azure-core",
    "azure-identity",
    "azure-monitor-opentelemetry"
]

[project.scripts]
compliant-llm = "cli.main:main"

[tool.setuptools.package-data]
"core" = ["**/*.yaml"]
    