[project]
name = "nonebot_plugin_megumin"
version = "0.2.6"
description = "现在，你的群友可以触发失传已久的爆裂魔法了！"
authors = [
    {name = "youlanan", email = "ylanan@foxmail.com"},
]
dependencies = [
    "nonebot2>=2.4.2",
    "nonebot-plugin-alconna>=0.57.2",
    "nonebot-plugin-localstore>=0.7.4",
    "nonebot-plugin-uninfo>=0.7.3",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/youlanan/nonebot_plugin_megumin"
Repository = "https://github.com/youlanan/nonebot_plugin_megumin.git"
Documentation = "https://github.com/youlanan/nonebot_plugin_megumin#readme"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 
[tool.nonebot]
plugins = []
