[project]
name = "autonomous_identification"
version = "0.1.3"
description = "autonomous_identification"
authors = [
    { name = "todo", email = "todo@todo.com" }
]
dependencies = [
    "autonomous-proto>=0.1.4",
    "typer>=0.15.4",
    "rosbags>=0.10.10",
    "scipy>=1.15.3",
    "matplotlib>=3.10.3",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/discrete_k_identify"]
