   [build-system]
   requires = ["setuptools>=61.0"]
   build-backend = "setuptools.build_meta"

   [project]
   name = "shoebill_ai"
   version = "0.0.9"
   authors = [
       {name = "shoebill", email = "shoebill.hai@gmail.com"},
   ]
   description = "AI Agent Framework"
   readme = "README.md"
   requires-python = ">=3.10"
   classifiers = [
       "Programming Language :: Python :: 3",
       "License :: OSI Approved :: Apache Software License",
       "Operating System :: OS Independent",
   ]
   dependencies = [
       "requests~=2.32.3",
       "pillow~=11.2.1",
       "python-magic-bin~=0.4.14",
       "ollama~=0.1.6",
       "h_message_bus~=0.0.41",
       "croniter~=2.0.1",
       "pytz~=2024.1"
   ]

   [project.optional-dependencies]
   dev = [
       "pytest",
       # Other development dependencies
   ]

   [tool.setuptools]
   # Include package data
   package-dir = {"" = "src"}

   [tool.setuptools.packages.find]
   where = ["src"]
   include = ["shoebill_ai*"]

   [tool.setuptools.package-data]
   "shoebill_ai" = ["resources/*.json"]
   "shoebill_ai.resources" = ["*.json"]
