[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "h4_test"
version = "0.0.7"
description = ""
authors = [
  { name="h4.heo", email="mungeol.heo@gmail.com" }
]
readme = "README.md"
license = { file="LICENSE" }
dependencies = ["google-cloud-bigquery"]
requires-python = ">=3.10"
