
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "apogee-sdk"
# dynamic = ["version"] # This dynamic method of getting version isn't working anymore. Update version here and in version.py
version = "0.0.4" # Also update version number in version.py
description = "Interface with Apogee sensors"
authors = [{name = "Apogee Instruments, Inc.", email = "developer@apogeeinstruments.com"}]
license = {file = "LICENSE"}
readme = "README.md"
dependencies = [
    "pyserial",  
    "bleak", 
    "asyncio"
]
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis",
]

[project.scripts]
apogee = "apogee.cli:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["apogee*"]
